notice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='notice'

urlpatterns = [
  path('', views.notice, name="notice"),
  path('detail/<int:id>', views.notice_detail, name="notice_detail"),
]

user/urls.py
from django.urls import path, include
from user import views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('signin/', views.signin, name='signin'),
    path('add_info/', views.add_info, name='add_info'),
    path('get_form/', views.get_form, name='get_form'),
    path('user_info/', views.user_info, name='user_info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

notice/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Create your models here.
class Notice(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  created_at = models.DateTimeField(default=timezone.now)

notice/views.py
from django.shortcuts import render
from .models import Notice

# Create your views here.
def notice(request):
  notice = Notice.objects.all().order_by('-created_at')

  context = {'notice':notice}
  return render(request, 'notice/notice.html', context)

def notice_detail(request, id):
  notice = Notice.objects.get(pk=id)
  context = {'notice':notice}
  return render(request, 'notice/notice_detail.html', context)

templates/notice/notice.html
{% extends 'base.html' %}

{% load static %}

{% block head_meta %}
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/notice.css' %}">
<link rel="stylesheet" href="{% static 'css/notice_footer.css' %}">
{% endblock %}


{% block content %}
<div class="list-container">
    <h2 class="top">공지사항</h2>
    <ul class="list">
        {% for post in notice %}
        <li class="list-row">
            <a href="{% url 'notice:notice_detail' post.id %}">
                <div class="title">{{post.title}}</div>
                <div class="date">{{post.created_at|date:'Y.m.d'}}</div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/notice.js' %}"></script>
{% endblock %}

templates/notice/notice_detail.html
{% extends 'base.html' %}

{% load static %}

{% block head_meta %}
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/notice_detail.css' %}">
<link rel="stylesheet" href="{% static 'css/notice_footer.css' %}">
{% endblock %}

{% block head_script %}
{% endblock %}

{% block content %}
<div class="notice-detail">
    <h2 class="top">공지사항</h2>
    <!-- <h2 class="test"></h2> -->
    <div class="detail">
        <div class="detail-header">
            <div class="title">
                {{notice.title}}
            </div>
            <div class="date">
                {{notice.created_at|date:'Y.m.d'}}
            </div>
        </div>
        <div class="detail-body">
            {{notice.content |linebreaks}}
        </div>
        <div class="detail-footer">
            <a href="{% url 'notice:notice' %}">
                <div class="button">
                    목록으로 돌아가기
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'js/notice.js' %}"></script>
{% endblock %}