notice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='notice'

urlpatterns = [
  path('', views.notice, name="notice"),
  path('detail/<int:id>', views.notice_detail, name="notice_detail"),
]

topic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='topic'

urlpatterns = [
    path('', views.topic_list, name="list"),
    path('<int:topic_id>/check/', views.check_selection, name="check_selection"),
    path('<int:topic_id>/', views.topic_select, name="select"),
    path('<int:topic_id>/result/', views.topic_result, name="result"),
    path('request/', views.user_request, name="request"),
]

user/urls.py
from django.urls import path, include
from user import views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('signin/', views.signin, name='signin'),
    path('add_info/', views.add_info, name='add_info'),
    path('get_form/', views.get_form, name='get_form'),
    path('user_info/', views.user_info, name='user_info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

templates/base.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>톺톡</title>

  {% block head_meta %}
  {% endblock %}
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169034644-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-169034644-1');
  </script>
  <script data-ad-client="ca-pub-6059842750992024" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  <script src="{% static 'js/base.js' %}"></script>
  {% block head_script %}
  {% endblock %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/reset.css' %}">
  {% block head_link %}
  {% endblock %}

  <!-- Facebook Pixel Code -->
  <script>
  !function(f,b,e,v,n,t,s)
  {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '3230620843722411');
  fbq('track', 'PageView');
  </script>
  <noscript><img height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=3230620843722411&ev=PageView&noscript=1"
  /></noscript>
  <!-- End Facebook Pixel Code -->
</head>

<body>
  <div class="wrapper">
    <header>
      <div class="header">
        <div class="header-contents">
          <div class="menu-btn">
            <img id="open" onclick="menuSwitch(this)" src="{% static 'img/menu.png' %}">
          </div>
          <div class="menu-box">
            <ul>
              <a href="{% url 'notice:notice' %}">
                <li><img src="{% static 'img/notice.png' %}" alt="" height="18px">공지사항</li>
              </a>
              {% if request.user.is_active %}
              <a href="javascript:void(0);" onclick="logout()">
                <li><img src="{% static 'img/user.png' %}">로그아웃</li>
              </a>
              <a href="{% url 'user_info' %}">
                <li><img src="{% static 'img/home.png' %}" alt="" height="20px">마이페이지</li>
              </a>
              {% else %}
              <a href="{% url 'signin' %}">
                <li><img src="{% static 'img/user.png' %}" alt="" height="20px">회원가입/로그인</li>
              </a>
              {% endif %}
            </ul>
          </div>
          <!-- <div class="user-icon">
          <img src="{% static 'img/user_icon.png' %}">
        </div>         -->
          <div class="header-title">
            <a href="{% url 'topic:list' %}">톺톡</a>

          </div>
        </div>
      </div>

      <div class="side-menu">
        <div class="side-menu-header">
        </div>
        <div class="menu-contents">
          <ul>
            {% if request.user.is_active %}
            <a href="javascript:void(0);" onclick="logout()">
              <li>로그아웃</li>
            </a>
            {% else %}
            <a href="{% url 'signin' %}">
              <li>회원가입/로그인</li>
            </a>
            {% endif %}
            <a href="{% url 'user_info' %}">
              <li>마이페이지</li>
            </a>
            <a href="{% url 'notice:notice' %}">
              <li>공지사항</li>
            </a>
          </ul>
        </div>
      </div>

    </header>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <footer>
      <div class="contents">
        <div>Copyright © 톺톡</div>
        <div style="display: inline-block;"><i class="fa fa-envelope" aria-hidden="true"></i> 문의 메일 : weall.co@gmail.com
        </div>
      </div>
    </footer>

  </div>
  {% block extra_js %}
  {% endblock %}
</body>

</html>