notice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='notice'

urlpatterns = [
  path('', views.notice, name="notice"),
  path('detail/<int:id>', views.notice_detail, name="notice_detail"),
]

topic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='topic'

urlpatterns = [
    path('', views.topic_list, name="list"),
    path('<int:topic_id>/check/', views.check_selection, name="check_selection"),
    path('<int:topic_id>/', views.topic_select, name="select"),
    path('<int:topic_id>/result/', views.topic_result, name="result"),
    path('request/', views.user_request, name="request"),
]

user/urls.py
from django.urls import path, include
from user import views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('signin/', views.signin, name='signin'),
    path('add_info/', views.add_info, name='add_info'),
    path('get_form/', views.get_form, name='get_form'),
    path('user_info/', views.user_info, name='user_info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

notice/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Create your models here.
class Notice(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  created_at = models.DateTimeField(default=timezone.now)

topic/models.py
from django.db import models
from django.utils import timezone
from user.models import User

# Integer 필드 최댓값 최솟값 설정을 위한 임포트
from django.core.validators import MinValueValidator, MaxValueValidator

class Topic(models.Model):
  thumb_image = models.ImageField()
  title = models.CharField(max_length=45)
  author = models.ForeignKey(User, related_name="topics", on_delete=models.CASCADE)
  content = models.TextField()
  # 후에 게시판을 나누게 될 경우 고려
  # category = models.IntegerField()
  selection_amount = models.IntegerField(default=0)
  hot_topic = models.BooleanField(default=False)
  created_at = models.DateTimeField(auto_now=timezone.now())

class Selection(models.Model):
  topic = models.ForeignKey(Topic, related_name="selections", on_delete=models.CASCADE)
  image = models.ImageField(null=True, blank=True)
  description = models.CharField(max_length=20)
  created_at = models.DateTimeField(auto_now=timezone.now())

  def save(self, *args, **kwargs):
    topic = self.topic
    topic.selection_amount += 1
    topic.save()
    super().save(*args, **kwargs)

    # delete 시 삭제 항목

class Pick(models.Model):
  topic = models.ForeignKey(Topic, related_name="picks", on_delete=models.CASCADE)
  author = models.ForeignKey(User, related_name="picks", on_delete=models.CASCADE)
  selection = models.IntegerField(validators=[
    MinValueValidator(1), 
    MaxValueValidator(4),
  ], null=True)
  # age_range, gender 삭제 (2020-08-03)
  created_at = models.DateTimeField(auto_now=timezone.now())
  updated_at = models.DateTimeField(default=timezone.now)
  
class DailyPick(models.Model):
  topic = models.ForeignKey(Topic, related_name="daily", on_delete=models.CASCADE, null=True, blank=True)
  pick1 = models.IntegerField()
  pick2 = models.IntegerField()
  pick3 = models.IntegerField()
  pick4 = models.IntegerField()
  created_at = models.DateTimeField(auto_now=timezone.now())

notice/views.py
from django.shortcuts import render
from .models import Notice

# Create your views here.
def notice(request):
  notice = Notice.objects.all().order_by('-created_at')

  context = {'notice':notice}
  return render(request, 'notice/notice.html', context)

def notice_detail(request, id):
  notice = Notice.objects.get(pk=id)
  context = {'notice':notice}
  return render(request, 'notice/notice_detail.html', context)

topic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Selection, Pick, DailyPick
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from user.models import User
from django.utils import timezone
import datetime

def convert(topic_list): 
    return tuple(i[0] for i in topic_list)

# 데일리 데이터 저장 부분
def store_daily_pick():
  topics = Topic.objects.all()

  for topic in topics:
    picks = topic.picks.all()

    todaypick = DailyPick()
    todaypick.topic = topic
    todaypick.pick1 = picks.filter(selection=1).count()
    todaypick.pick2 = picks.filter(selection=2).count()
    todaypick.pick3 = picks.filter(selection=3).count()
    todaypick.pick4 = picks.filter(selection=4).count()
    todaypick.save()

# 핫 토픽 설정 부분
# updated_at 필드를 추가해서 기존에 설문에 참여했던 사람이 값을 변경했을 경우도 값에 포함될 수 있게 함.
# 매일 오전 00시 00분에 실행되게 데코레이터 사용
def set_hot_topic():
  yesterday = datetime.date.today() - datetime.timedelta(days=1)
  today_picks = Pick.objects.filter(updated_at__date=yesterday)

  topic_list = {
  }
  hot_topic_list = []

  for pick in today_picks:
    if pick.topic.id in topic_list:
      topic_list[pick.topic.id] += 1
    else:
      topic_list[pick.topic.id] = 1

  topic_list = sorted(topic_list.items(), key=(lambda x : x[0]), reverse=True)

  for topic in topic_list:
    if len(hot_topic_list) >= 3:
      if hot_topic_list[2][1] < topic[1]:
        hot_topic_list[2] = topic
    else:
      hot_topic_list.append(topic)
    hot_topic_list = sorted(hot_topic_list, key=(lambda x : x[1]), reverse=True)

  hot_topic_id = convert(hot_topic_list)

  Topic.objects.filter(hot_topic=True).update(hot_topic=False)

  Topic.objects.filter(id__in=hot_topic_id).update(hot_topic=True)

# result page에 접속할때마다 현재까지 결과 값을 확인하는 과정
def set_data(objects):
  selections = [x for x in range(1, objects.selection_amount+1)]
  ages = [10, 20, 30, 40, 50, 60]
  genders = ['male','female']

  result = {}

  for selection in selections:
    picks = objects.picks.filter(selection=selection)
    result["selection_" + str(selection)] = picks.count()
    for age in ages:
      result["selection_" + str(selection) + "_" + str(age)] = picks.filter(selection=selection, author__age_range=age).count()
      for gender in genders:
        result["selection_" + str(selection) + "_" + str(gender)] = picks.filter(selection=selection, author__gender=gender).count()
        result["selection_" + str(selection) + "_" + str(age) + "_" + str(gender)] = picks.filter(selection=selection, author__age_range=age, author__gender=gender).count()
  
  return result

def topic_list(request):
  topics = Topic.objects.all().order_by('-created_at')
  hot_topics = Topic.objects.filter(hot_topic=True)

  return render(request, 'topic/list.html', {
    'topics' : topics,
    'hot_topics' : hot_topics,
  })

@login_required(login_url='/auth/signin/')
@user_passes_test(lambda u: u.gender and u.age_range and u.sido and u.sigungu, login_url='/auth/add_info/')
def check_selection(request, topic_id):
  topic = get_object_or_404(Topic, pk=topic_id)

  if topic.picks.filter(author=request.user).exists():
    return redirect('topic:result', topic.id)
  else:
    return render(request, 'topic/select.html', {
      'topic' : topic,
    })

@login_required(login_url='/auth/signin/')
@user_passes_test(lambda u: u.gender and u.age_range and u.sido and u.sigungu, login_url='/auth/add_info/')
def topic_select(request, topic_id):
  topic = get_object_or_404(Topic, pk=topic_id)

  if request.method == 'POST':
    u_gender = 0 if (request.user.gender == 'male') else 1

    u_pick = int(request.POST.get('pick', '0'))

    if u_pick < 1 or u_pick > topic.selection_amount:
      return redirect('topic:select', topic.id)
    
    
    pick, created = Pick.objects.get_or_create(
      author=request.user,
      topic=topic,
    )

    if created:
        pick.selection = u_pick
        pick.updated_at = timezone.now()
        pick.save()
    else:
      if not pick.selection == u_pick:
        pick.selection = u_pick
        pick.updated_at = timezone.now()
        pick.save()
    return redirect('topic:result', topic.id)


  return render(request, 'topic/select.html', {
    'topic' : topic,
  })


@login_required(login_url='/auth/signin/')
def topic_result(request, topic_id):
  topic = get_object_or_404(Topic, pk=topic_id)
  try:
    pick = topic.picks.get(author=request.user)  
    data = set_data(topic)
    return render(request, 'topic/result.html', {
      'topic' : topic,
      'pick' : pick,
      'data' : data,
    })
  except:
    return redirect('topic:select', topic_id)
  
  
def user_request(request):
  return render(request, 'topic/request.html')

templates/topic/list.html
{% extends 'base.html' %}

{% load static %}

{% block head_meta %}
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/carousel.css' %}">
{% endblock %}

{% block head_script %}
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/list.js' %}"></script>
{% endblock %}{% block content %}

<div class="hot-topic">
  <div class="owl-carousel owl-theme">
    {% for hot_topic in hot_topics %}
    <div class="item">
      <div class="thumb-box" style="background-image: url({{hot_topic.thumb_image.url}});">
      </div>
      <div class="hot-topic-contents">
        <div class="hot-topic-title">
          {{hot_topic.title}}
        </div>
        <div class="hot-topic-subtitle">
          {{hot_topic.content}}
        </div>
      </div>
      <a href="{% url 'topic:check_selection' hot_topic.pk %}">
        <div class="voting-btn">
          투표하기
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
<script>
  $('.owl-carousel').owlCarousel({
    items: 1,
    loop: true,
    margin: 0,
    nav: false,
    dots: true,
    autoplay: true,
    autoplayTimeout: 2500,
    autoplayHoverPause: true
  })

</script>


<div class="list-title">
  최신 토픽
</div>

<div class="topic-list">
  {% for topic in topics %}
  <div class="topic-card">

    <a href="{% url 'topic:check_selection' topic.pk %}">
      <div class="topic-contents">
        <div class="topic-thumb"><img src="{{topic.thumb_image.url}}"></div>
        <div class="topic-text">
          <div class="topic-title">{{topic.title}}</div>
          <div class="topic-subtitle">{{topic.content}}</div>
          <div class="participant">{{topic.picks.all.count}}명 참여</div>
        </div>
      </div>

    </a>
  </div>
  {% endfor %}

</div>
</div>

{% endblock %}

templates/topic/notice.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/notice.css' %}">
{% endblock %}

{% block content %}
<div class="list-container">
    <h2 class="top">공지사항</h2>
    <ul class="list">
        {% for post in notice %}
        <li class="list-row">
            <a href="{% url 'topic:notice_detail' post.id %}">
                <div class="title">{{post.title}}</div>
                <div class="date">{{post.created_at|date:'Y.m.d'}}</div>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/topic/notice_detail.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'css/notice_detail.css' %}">
{% endblock %}

{% block content %}
<div class="notice-detail">

    <h2 class="top">공지사항</h2>

    <div class="detail">
        <div class="detail-header">
            <div class="title">
                서비스서비스 서비스서비스 정상복구 공지
            </div>
            <div class="date">
                2020.05.29
            </div>
        </div>
        <div class="detail-body">
            안녕하세요 어디누구누구 입니다.
        </div>
        <div class="detail-footer">
            <a href="{% url 'topic:notice' %}">
                <div class="button">
                    목록으로 돌아가기
                </div>
            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/topic/request.html
{% extends 'base.html' %}

{% load static %}

{% block head_meta %}
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/request.css' %}">
{% endblock %}

{% block head_script %}
{% endblock %}

{% block content %}
<div class="request-container">
    <div class="button right">
        <div>새 토픽 요청하기</div>
    </div>
    <h2 class="top">요청하기</h2>
    <ul class="list">
        <li class="list-row">
            <div class="thumb">
                <img src="{% static 'img/no.png' %}">
            </div>
            <div class="content">
                <div class="title">
                    요청요청요청요청요청요청요청요청요청요청
                </div>
                <div class="like">
                    추천
                </div>
            </div>
        </li>
        <li class="list-row">
            <div class="thumb">
                <img src="{% static 'img/no.png' %}">
            </div>
            <div class="content">
                <div class="title">
                    요청요청요청요청요청요청요청요청요청요청
                </div>
                <div class="like">
                    추천
                </div>
            </div>
        </li>
    </ul>
</div>
{% endblock %} 

templates/topic/select.html
{% extends 'base.html' %}

{% load static %}


{% block head_meta %}
<meta name="description" content="{{ topic.description }}" />
<meta property="og:title" content="{{ topic.title }}" />
<meta property="og:image" content="{{ topic.thumb_image.url }}" />
<meta property="og:description" content="{{ topic.description }}" />
{% endblock %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/select.css' %}">
{% endblock %}

{% block head_script %}
<script src="{% static 'js/select.js' %}"></script>
{% endblock %}

{% block content %}
<div class="topic-wrapper">
  <div class="topic-background">
    <div class="topic-thumb" style="background-image: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url('{{topic.thumb_image.url}}')">
      <div class="topic-title-box">
        <div class="topic-title">{{topic.title}}</div>
        <div class="topic-subtitle">{{topic.content}}</div>
      </div>
    </div>
    
   
  </div>

  <div class="select-wrapper">
    <div class="select-box">
      {% for selection in topic.selections.all%}
      <div data="{{forloop.counter}}" class="selection" style="background: url({{selection.image.url}}); background-size: cover; background-position: center;">
        <div class="selection-text-wrapper">
          <div class="selection-text">
            {{selection.description}}
          </div>
        </div>
      </div>
      {% endfor %}

      <form action="{% url 'topic:select' topic.pk %}" method="POST" class="voting-form">
        {% csrf_token %}
        <input type="hidden" name="pick">
        <input type="submit" value="투표하기" class="voting-btn" disabled="true">
      </form>
    </div>
  </div>
  
  <div>

  </div>
</div>

{% endblock %}

{% block extra_js %}
{% endblock %}