topic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name='topic'

urlpatterns = [
    path('', views.topic_list, name="list"),
    path('<int:topic_id>/check/', views.check_selection, name="check_selection"),
    path('<int:topic_id>/', views.topic_select, name="select"),
    path('<int:topic_id>/result/', views.topic_result, name="result"),
    path('request/', views.user_request, name="request"),
]

user/urls.py
from django.urls import path, include
from user import views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('signin/', views.signin, name='signin'),
    path('add_info/', views.add_info, name='add_info'),
    path('get_form/', views.get_form, name='get_form'),
    path('user_info/', views.user_info, name='user_info'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth.models import BaseUserManager as DefaultUserManager
# Integer 필드 최댓값 최솟값 설정을 위한 임포트
from django.core.validators import MinValueValidator, MaxValueValidator

class UserManager(DefaultUserManager):
    def get_or_create_kakao_user(self, user_pk, extra_data):

        user = User.objects.get(pk=user_pk)     
        user.user_type = 'K'
        user.nickname = extra_data['properties'].get('nickname','')
        user.gender = extra_data['kakao_account'].get('gender','')
        user.age_range = self.save_age_range(extra_data['kakao_account'].get('age_range',''))
        user.save()

        return user

    def save_age_range(self, age_range):
        age = 0
        if age_range == '15~19':
            age = 10
        elif age_range == '20~29':
            age = 20
        elif age_range == '30~39':
            age = 30
        elif age_range == '40~49':
            age = 40
        elif age_range == '50~59':
            age = 50
        elif age_range == '60~69':
            age = 60
        return age

    def create_user(self, username, password=None):        
        
        user = self.model(                
            username = username        
        )        
        user.set_password(password)        
        user.save(using=self._db)        

        return user     

    def create_superuser(self, username, password ):        
       
        user = self.create_user(                   
            username = username,            
            password=password        
        )        
        user.is_admin = True        
        user.is_superuser = True        
        user.is_staff = True        
        user.save(using=self._db)        
        return user 

class User(AbstractBaseUser,PermissionsMixin):

    objects = UserManager()
    
    username = models.CharField(
        max_length=20,
        null=False,
        unique=True
    )
    user_type = models.CharField(max_length=10)
    nickname = models.CharField(max_length=40)
    gender = models.CharField(max_length=10)
    age_range = models.IntegerField(validators=[
    MinValueValidator(0), 
    MaxValueValidator(100),
    ],
    null=True,
    )
    sido = models.CharField(max_length=10, null=True)
    sigungu = models.CharField(max_length=15, null=True)

    is_active = models.BooleanField(default=True)    
    is_admin = models.BooleanField(default=False)    
    is_superuser = models.BooleanField(default=False)    
    is_staff = models.BooleanField(default=False)   
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'

user/forms.py
from django import forms
from .models import User
from .region import Sigunu

age_range = (
    ('10','10대'),
    ('20','20대'),
    ('30','30대'),
    ('40','40대'),
    ('50','50대'),
    ('60','60대')
    )

gender = (
    ('male','남성'),
    ('female','여성')
)

sido = (
    ('서울','서울'),
    ('인천','인천'),
    ('대전','대전'),
    ('광주','광주'),
    ('대구','대구'),
    ('부산','부산'),
    ('울산','울산'),
    ('경기','경기'),
    ('충북','충북'),
    ('충남','충남'),
    ('전북','전북'),
    ('전남','전남'),
    ('강원','강원'),
    ('경북','경북'),
    ('경남','경남'),
    ('제주','제주'),    
)

class AddForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['gender','age_range']

    def __init__(self, *args, **kwargs):
        super(AddForm, self).__init__(*args, **kwargs)
        self.fields['age_range'] = forms.ChoiceField(
            label=False,
            choices=age_range,
            )
        self.fields['gender'] = forms.ChoiceField(
            label=False,
            choices=gender,
            )

class EditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['gender','age_range']

    def __init__(self, *args, **kwargs):
        super(EditForm, self).__init__(*args, **kwargs)
        self.label_suffix = ''
        # self.fields['nickname'] = forms.CharField(
        #     label=False,
        # )
        self.fields['age_range'] = forms.ChoiceField(
            label=False,
            choices=age_range,
            )
        self.fields['gender'] = forms.ChoiceField(
            label=False,
            choices=gender,
            widget=forms.RadioSelect
            )

    
class regionForm(forms.Form):
    class Meta:
        model = User
        fields = ['sido','sigungu']

    def __init__(self, *args, **kwargs):
        super(regionForm, self).__init__(*args, **kwargs)
        
        _sido = '서울'
        print(args)
        for arg in args:
            for k,v in arg.items():
                if k == 'sido':
                    _sido = v

        self.fields['sido'] = forms.ChoiceField(
            label=False,
            choices=sido,
        )
        self.fields['sigungu'] = forms.ChoiceField(
            label=False,
            choices=Sigunu().get_list(_sido)
        )

    def set_region(self, selected_sido='서울'):
        self.fields['sido'] = forms.ChoiceField(
            label=False,
            choices=sido,
            initial=selected_sido,            
        )
        self.fields['sigungu'] = forms.ChoiceField(
            label=False,
            choices=Sigunu().get_list(sigunu=selected_sido),         
        )

        return self

user/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .forms import AddForm, regionForm, EditForm
from .models import User
from topic.models import Pick
from point.models import Point

def signin(request):
        return render(request, 'user/signin.html')
def add_info(request):
    # wrong_flag = User.objects.get(pk=request.user.id)
    # 계속 수정해야할때 들어가야되서 일부러 not 넣어둠 나중에 지워야함.
    if request.method == 'POST':
        addform = AddForm(request.POST)
        regionform = regionForm(request.POST)
        if addform.is_valid() and regionform.is_valid():
            user = User.objects.get(pk=request.user.id)
            user.age_range = addform.cleaned_data['age_range']
            user.gender = addform.cleaned_data['gender']
            user.sido = regionform.cleaned_data['sido']
            user.sigungu = regionform.cleaned_data['sigungu']
            user.save()
        return redirect('topic:list')
    else:
        addform = AddForm()
        regionform = regionForm()
        context = {'addform':addform,'regionform':regionform}
        return render(request, 'user/add_info.html', context)

def get_form(request):
    form = regionForm()
    form = form.set_region(selected_sido=request.GET.get('sido','서울'))
    return HttpResponse(form)


def user_info(request):

    user = User.objects.get(pk=request.user.pk)
    
    # 포인트 올리기
    # p = Point.objects.addPoint(request.user.point.pk,100)

    context = {
        'user':user,
        'picks':Pick.objects.filter(author=request.user).order_by('-updated_at')
    }
    return render(request, 'user/user_info.html', context)

def edit_profile(request):
    if request.method == 'POST':
        editform = EditForm(request.POST)
        regionform = regionForm(request.POST)
        if editform.is_valid() and regionform.is_valid():
            user = User.objects.get(pk=request.user.id)
            # user.nickname = editform.cleaned_data['nickname']
            user.age_range = editform.cleaned_data['age_range']
            user.gender = editform.cleaned_data['gender']
            user.sido = regionform.cleaned_data['sido']
            user.sigungu = regionform.cleaned_data['sigungu']
            user.save()
        return redirect('user_info')
    else:            
        editform = EditForm()
        regionform = regionForm().set_region(selected_sido=request.user.sido)
        
        user_data = ''+request.user.nickname+','+str(request.user.age_range)+','+request.user.gender
        context = {
            'editform':editform,
            'regionform':regionform,
            'user_data':user_data
        }

        return render(request, 'user/edit_profile.html', context)

templates/user/add_info.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/add_info.css' %}">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="{% static 'js/add_info.js' %}"></script>
    <title>톺톡</title>

</head>

<body>

    <div class="signin-page">
        <div class="logo">
            <a href="{% url 'topic:list' %}"><h1>톺톡</h1></a>
        </div>
        <div class="signin-box">
            <div class="title">
                <span style="color: #f7e600;">Kakao</span>에서 추가정보를 <br> 받지 못했습니다.
            </div>
            <div class="btn-box">
                <form action="{% url 'add_info' %}" method="POST">
                    {% csrf_token %}
                    <div style="margin-top: 15px;">성별/나이</div>
                    <div id="add">{{addform}}</div>
                    <div style="margin-top: 15px;">지역</div>
                    <div id="region">{{regionform}}</div>                    
                    <input type="submit" value="확 인">
                </form>
            </div>
            
            <div class="sub-title">
                수집된 정보는 통계자료에만 사용되며 <br> 다른 목적으로 사용되지 않습니다.
            </div>
            
        </div>
    </div>
</body>

</html>

templates/user/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block head_link %}
<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
{% endblock %}

{% block head_script %}
<script>
    var user_data = '{{user_data}}'
</script>
<script src="{% static 'js/edit_profile.js' %}"></script>
{% endblock %}

{% block content %}
<div class="edit_wrapper">
    <div class="edit-title">
        프로필 수정
    </div>
    <div class="editform-box">
        <form action="{% url 'edit_profile' %}" method="POST">
            {% csrf_token %}
        <!-- <div class="setting">
            <span class="label">이름</span>
            <input type="text" name="nickname" required="" autocomplete="off">
        </div>         -->
        <div class="setting">
            <span class="label">성별</span>
                <label id="label-male" class="radio-container" for="id_gender_0" onclick="check_radio(this)"><input type="radio" name="gender" value="male" id="id_gender_0"> 남자</label>
                <label id="label-female" class="radio-container" for="id_gender_1" onclick="check_radio(this)"><input type="radio" name="gender" value="female" id="id_gender_1"> 여자</label>
        </div>        
        <div class="setting">
            <span class="label">연령대</span>
            <select name="age_range" id="id_age_range">
                <option value="10">10대</option>
                <option value="20">20대</option>
                <option value="30">30대</option>
                <option value="40">40대</option>
                <option value="50">50대</option>
                <option value="60">60대</option>
            </select>
        </div>        
        <div id="region" class="setting">
            <span class="label">지역</span>
            {{regionform}}
        </div>
        <div class="btn-box">
            <a href="{% url 'user_info' %}"><button type="button" class="btn btn-cancel">취소</button></a>
            <button type="submit" class="btn btn-submit">확인</button>            
        </div>
    </form>
    </div>
</div>
{% endblock %}

templates/user/signin.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
    <title>톺톡</title>

</head>

<body>

    <div class="signin-page">
        <div class="logo">
            <a href="{% url 'topic:list' %}"><h1>톺톡</h1></a>
        </div>
        <div class="signin-box">
            <div class="title">
                간단하게 가입하고,<br>의견을 공유하세요!
            </div>
            <div class="btn-box">
                <a href="{% provider_login_url 'kakao' %}"><img class="kakao" src="{% static 'img/kakao.png' %}"></a>
            </div>
            
        </div>
    </div>
</body>

</html>

templates/user/user_info.html
{% extends 'base.html' %}
{% load static %}

{% block head_link %}
<link rel="stylesheet" href="{% static 'css/user_info.css' %}">
{% endblock %}

{% block head_script %}
<script src="{% static 'js/user_info.js' %}"></script>
{% endblock %}

{% block content %}
<div class="contents-wrapper">
    <div class="info-contents">
        <div class="my-profile">
            <img src="{% static 'img/user_profile.png' %}" alt="">
            <div class="inner">
                <div class="name">{{user.nickname}}</div>
                <div class="region">{{user.sido}} {{user.sigungu}}</div>
                <div class="age">{{user.age_range}}대 {% if user.gender == 'female' %}여자{% else %}남자{%endif%}</div>
            </div>
            <a href="{% url 'edit_profile' %}">
                <div class="edit-btn">프로필 수정</div>
            </a>
        </div>
        <div class="count-wrapper">
            <div class="count-box">
                포인트
                <div class="point-count">추가 예정</div>
            </div>
            <div class="split-border-r"></div>
            <div class="count-box">
                참여한 토픽
                <div class="topic-count">
                    {{picks.count}}
                </div>
            </div>
        </div>
    </div>
    <div class="topic-contents">
        <div class="topic-list">
            {% for pick in picks|slice:":4" %}
            <div class="topic">
                <a href="{% url 'topic:result' pick.topic.pk %}">
                    <div class="thumb-box" style="background-image: url({{pick.topic.thumb_image.url}});">
                        <div class="participation">{{pick.updated_at|date:'Y.m.d'}}</div>
                    </div>

                    <div class="topic-text">
                        <div class="topic-title">
                            {{pick.topic.title}}
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>

        <div class="more-topic">
            <a href="{% url 'topic:list' %}">
            더 많은 토픽 보러가기 <i class="fa fa-angle-right" aria-hidden="true"></i>
        </a>
        </div>
    </div>
    <div>
    </div>
</div>
{% endblock %}